/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvancedToolsDialog: typeof import('./src/components/AdvancedToolsDialog.vue')['default']
    DebugInspector: typeof import('./src/components/DebugInspector.vue')['default']
    DemoOverlay: typeof import('./src/components/demo/DemoOverlay.vue')['default']
    DicomTagDialog: typeof import('./src/components/DicomTagDialog.vue')['default']
    DicomView: typeof import('./src/components/DicomView.vue')['default']
    ImageBox: typeof import('./src/components/ImageBox.vue')['default']
    LlmChatPanel: typeof import('./src/components/llm/LlmChatPanel.vue')['default']
    SegmentationPanel: typeof import('./src/components/SegmentationPanel.vue')['default']
    SeriesList: typeof import('./src/components/SeriesList.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    VrTfEditor: typeof import('./src/components/VrTfEditor.vue')['default']
    WindowPresetMenu: typeof import('./src/components/WindowPresetMenu.vue')['default']
  }
}
